import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import {Providers} from "./providers";
import Footer from './components/Footer';
import AuthProvider from './auth/Provider';

const roboto = Roboto({ subsets: ['latin'], weight: ['100', '300', '400', '500', '700', '900' ] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
          <Providers>
            {children}
          </Providers>
      </body>
    </html>
  )
}
